name: deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: form-playground
  IAC_TARGET: production
  IAC_FILE: formplayground.yaml

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: set-version
        uses: actions/github-script@v6
        with:
          script: |
            const version = context.payload.inputs?.version || context.sha.slice(0, 7);
            core.setOutput('version', version);

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: |
          pnpm install
          pnpm build:form
          pnpm build:server
          pnpm build:app
          mv ./packages/playground/dist ./packages/server/app
      - run: |
          cd packages/server
          DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ needs.setup.outputs.version }}"
          docker build -t ${DOCKER_IMAGE} .
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${DOCKER_IMAGE}

  gitops:
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: okyiww/IaC
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: iac
      - name: update iac file
        run: |
          cd iac
          if [ -f "${{ env.IAC_TARGET }}/${{ env.IAC_FILE }}" ]; then
            sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ needs.setup.outputs.version }}|' "${{ env.IAC_TARGET }}/${{ env.IAC_FILE }}"
          elif [ -f "${{ env.IAC_TARGET }}/${{ env.IAC_FILE }}.bak" ]; then
            mv "${{ env.IAC_TARGET }}/${{ env.IAC_FILE }}.bak" "${{ env.IAC_TARGET }}/${{ env.IAC_FILE }}"
            sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ needs.setup.outputs.version }}|' "${{ env.IAC_TARGET }}/${{ env.IAC_FILE }}"
          else
            echo "Error: ${{ env.IAC_TARGET }}/${{ env.IAC_FILE }} or its backup file not found"
            exit 1
          fi
      - name: commit and push
        run: |
          cd iac
          git config user.name okyiww
          git config user.email okyiww@gmail.com
          git add .
          git commit -m "chore(release): update ${{ env.PROJECT_NAME }} to ${{ needs.setup.outputs.version }}"
          git push
